export const LOAD_MENU_START = 'LOAD_MENU_START';
export const LOAD_MENU_SUCCESS = 'LOAD_MENU_SUCCESS';
export const LOAD_MENU_FAILED = 'LOAD_MENU_FAILED';
export const CLEAR_DATA_MENU = 'CLEAR_DATA_MENU';


// ORDER
export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM';
export const REMOVE_NOTE_ITEM = 'REMOVE_NOTE_ITEM';
export const SHOW_INPUT_ITEM = 'SHOW_INPUT_ITEM';
export const CHANGE_INPUT_ITEM = 'CHANGE_INPUT_ITEM';