export const LOAD_MENU_START = 'LOAD_MENU_START';
export const LOAD_MENU_SUCCESS = 'LOAD_MENU_SUCCESS';
export const LOAD_MENU_FAILED = 'LOAD_MENU_FAILED';
export const CLEAR_DATA_MENU = 'CLEAR_DATA_MENU';

//Menu
export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU';
export const LOAD_MORE = 'LOAD_MORE';
export const SEARCH_MENU = 'SEARCH_MENU';
export const BACK_STATE = 'BACK_STATE';

// ORDER
export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM';
export const REMOVE_NOTE_ITEM = 'REMOVE_NOTE_ITEM';
export const SHOW_INPUT_ITEM = 'SHOW_INPUT_ITEM';
export const CHANGE_INPUT_ITEM = 'CHANGE_INPUT_ITEM';
export const CHANGE_QTY_ITEM = 'CHANGE_QTY_ITEM';
export const CLEAR_ITEM = 'CLEAR_ITEM';

//Transaction
export const CREATE_TRX_START = 'CREATE_TRX_START';
export const CREATE_TRX_SUCCESS = 'CREATE_TRX_SUCCESS';
export const CREATE_TRX_FAILED = 'CREATE_TRX_FAILED';

//Detail
export const DETAIL_TRX_START = 'DETAIL_TRX_START';
export const DETAIL_TRX_SUCCESS = 'DETAIL_TRX_SUCCESS';
export const DETAIL_TRX_FAILED = 'DETAIL_TRX_FAILED';

export const LOAD_TRX_START = 'LOAD_TRX_START';
export const LOAD_TRX_SUCCESS = 'LOAD_TRX_SUCCESS';
export const LOAD_TRX_FAILED = 'LOAD_TRX_FAILED';